version: '3.7'

services:
  python_total:
    build: 
      context: ./
      dockerfile: Dockerfile.total
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - private
  python_history:
    build: 
      context: ./
      dockerfile: Dockerfile.history
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - private
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
    networks:
      - private
  grafana:
    image: grafana/grafana
    depends_on:
      - db
    networks:
      - private
      - public

networks:
  private:
    driver: overlay
  public:
    external: true

volumes:
  postgres_data:
    
