FROM python:3.9.7-alpine3.14

ADD history_pix.py /home/history_pix.py

RUN pip install --upgrade pip
RUN pip install requests 
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
RUN pip install psycopg2

CMD ["python", "/home/history_pix.py"]